name: Hprofile Testing and building
on: workflow_dispatch
env:
  AWS_REGION: us-east-2
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Setup java 11 to be default (sonar-scanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'

# Setup java 11 to be default (sonar-scanner requirement as of 5.x)
  BUILD_AND_PUBLISH:
    
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build & Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
         access_key: AKIA6ODUZV3B5QV7FO2Z
         secret_key: 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
         registry: 992382398147.dkr.ecr.us-east-1.amazonaws.com
         repo: actappvprofile
         region: us-east-1
         tags: latest
         daemon_off: false
         dockerfile: ./Dockerfile
         context: ./

  
