name: Ctesting dist

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  testing-dist:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4.1.6

        - name: Maven test
          run: mvn test

        - name: Checkstyle
          run: mvn checkstyle:checkstyle

        - uses: actions/setup-java@v4
          with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '21'

       
        - name: Setup SonarQube
          uses: warchant/setup-sonar-scanner@v7
   
   
        - name: SonarQube Scan
          run: sonar-scanner
             -Dsonar.host.url=${{ secrets.SONAR_URL }}
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
             -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
             -Dsonar.sources=src/
             -Dsonar.junit.reportsPath=target/surefire-reports/ 
             -Dsonar.jacoco.reportsPath=target/jacoco.exec 
             -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
             -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/

    


        

