name: Check dist

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  testing-dist:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4.1.6

        - name: Maven test
          run: mvn test

        - name: Checkstyle
          run: mvn checkstyle:checkstyle

        

